language: go

_sources: &repos
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0

_addons: &addon_conf
  apt:
    packages: ['gcc-multilib']
    sources: *repos

go:
  - 1.10

matrix:
  include:
    - os: linux
      env: TEST=1 TARGET=nrf52_blinky ARMGCC_VERSION=6.2.1
      addons: *addon_conf
    - os: linux
      env: TEST=3 TARGET=nrf52_blinky ARMGCC_VERSION=7.2.1
      addons: *addon_conf
    - os: osx
      osx_image: xcode9.2
      env: TEST=2 TARGET=stm32f4disc_blinky

before_install:
- printenv
- export GOPATH=$HOME/gopath
- chmod +x ci/*.sh
- go version
- ci/${TRAVIS_OS_NAME}_travis_install.sh
- newt version

install:
- echo "Skip default Go install step"

script:
- ${TRAVIS_BUILD_DIR}/ci/make_targets.sh
- newt install
- newt target show
- newt build $TARGET
- newt test all -e net/nimble/host,net/oic/test

cache:
  directories:
  - $HOME/TC
